username = input("Ваше имя?: ")
title = input("Заголовок заметки:")
content = input("Описание заметки:")
status = input("Статус заметки:")
created_date = input("Дата создания заметки:(Дата записывается в виде хх.хх.хххх, число, месяц, год)")
issue_date = input("Дата истечения заметки:(Дата записывается в виде хх.хх.хххх, число, месяц, год)")
print(username)
print(title)
print(content)
print(status)
print(created_date)
print(issue_date)
